name: LamDispensers
version: '${project.version}'
main: org.yusaki.lamdispensers.LamDispensers
api-version: '1.20'
depend: [YskLib]
folia-supported: true
commands:
  lamdispensers:
    description: Main command for LamDispensers
    usage: /lamdispensers reload
permissions:
  lamdispensers.reload:
    description: Allows reloading the plugin configuration
    default: op
